### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by keisuke-umezawa** [keisuke-umezawa/NICO2AI#1]
# 講義資料
- [x] Intoro

# Part 3. 他手法との比較 (20分)
- [x] 汎化誤差・交差検証 (復習)
- [x] 機械学習モデルの性能を決める要素 (特徴選択・前処理・線形性)
- [x] SVMとNNの比較
- [x] モデル選択

# 実践演習 (85分)
- [x] 課題1: Chainerを用いた多層パーセプトロンの実装 (30分)
第5回と同様、MNISTデータセットに対して今度はChainerで多層パーセプトロンを実装
- [ ] 課題2: 線形・ガウシアンSVMを用いたMNIST分類 (20分)
Scikit-learnを使いつつ、線形・ガウシアンSVMを用いた分類を行い、NNと比較
(適切なデータセットがあればMNIST以外のデータセットでの比較も考えられる)
- [x] 課題3: DropoutとBN (20分)
Dropout及びBNを課題1のコードに追加し、バリデーション誤差や正解率に対する影響を見る
各層の中間層の値を取り出して、その傾向を見る
- [x] 解説・コードレビュー (15分)
